version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    resource_class: small
    steps:
      - checkout
      - run: pip install jsonschema
      - run: jsonschema -i nests.json nests.schema.json
